project:
  type: website

website:
  title: "Mirko Ruf"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Über
        menu:
          - href: mirko.qmd
            text: "Über mich"
          - href: aktuelles.qmd
            text: Aktuelles
          - href: kontakt.qmd
            text: Kontakt
      - href: forschung.qmd
        text: Forschung
        menu:
          - href: doktorarbeit.qmd
            text: Doktorarbeit
          - href: vortraege.qmd
            text: Vorträge
          - href: publikationen.qmd
            text: Publikationen
      - href: lehre.qmd
        text: Lehre

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
