project:
  type: website

website:
  title: "Mirko Ruf"
  page-footer: "Made with Quarto and ♡️"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Über
      - href: forschung.qmd
        text: Forschung
      - href: lehre.qmd
        text: Lehre
      - href: kontakt.qmd
        text: Kontakt
format:
  html:
    theme: [cosmo, brand]
    css: styles.css
    toc: true
    lang: de
    # include-after-body: script.js

