project:
  type: website

website:
  title: "Mirko Ruf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: forschung.qmd
        text: Forschung
      - href: lehre.qmd
        text: Lehre
      - href: doktorarbeit.qmd
        text: Doktorarbeit
      - href: quellen.qmd
        text: Quellen

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



