project:
  type: website

website:
  title: "Mirko Ruf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - forschung.qmd
        text: Forschung
      - lehre.qmd
        text: Lehre
      - doktorarbeit.qmd
        text: Doktorarbeit

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



